### ISSUE TITLE
Possible to work on CH552?

### ISSUE THREAD

**Issue by DeqingSun** [NgoHungCuong/vnproch551#1]
Hi I just found this project and I'm curious if it is possible to write to a CH552 chip?

I got it compiled and captured the USB transaction. It seems the "Set Flash Address" command from WCHISPTool got pretty complicated.  And all following flash commands got different from your tool.

Would you mind sharing any suggestions on debugging/reverse engineering?

Thanks

--------  

Here is the 1st A3 command I captured.

unsigned char data[58] = 
{
	0xa3, 0x37, 0x00, 0x87, 0xf4, 0xbd, 0xe5, 0xd0, 0x19, 0x90, 0xea, 0x8d, 0xc0, 0x44, 0x0e, 0x9f, 
	0x53, 0x6d, 0x29, 0xca, 0x99, 0x88, 0x55, 0x16, 0x88, 0x80, 0x5a, 0x75, 0x5b, 0x78, 0x6a, 0xa7, 
	0xe4, 0xc4, 0x0f, 0x5b, 0x22, 0x38, 0x61, 0x97, 0x16, 0xa6, 0x7c, 0x59, 0xd3, 0xa2, 0x31, 0x7f, 
	0xd5, 0x88, 0xfc, 0xe4, 0x93, 0xc1, 0x36, 0xcc, 0x57, 0x41
};

**Comment by NgoHungCuong** [comment]
In WCHISP tool, there are many point call to GetTickCount, srand, rand... function. You must fix them.

**Comment by DeqingSun** [comment]
Thanks for your quick response. I'm not an expert in reverse engineering on PC. With some quick google search, I did locate 'MCU ISP & WCH.CN' in WCH55xISPDLL.dll with OLLYDBG. And I guess OLLYDBG may not be the best tool to do that. Would you mind recommending tools/methods you use?

Thanks

**Comment by NgoHungCuong** [comment]
I am using x64dbg and hexray/ida pro.

**Comment by DeqingSun** [comment]
Thank you, I'll see what I can do with it.

**Comment by NgoHungCuong** [comment]
Ok. You can share your code when you complete. Many thanks.

**Comment by DeqingSun** [comment]
Thanks for your help, I did find GetTickCount, srand, rand functions in subroutine 1000B0A0, by patching those calls with "mov eax, 0" (5byte) and "nop" (1byte), I did get exact same packet to your u8AddessCmd.

There is also a rand on 10002787, patching it will make byte 7 of A5 command always 0

Patched dll attached here, just in case anyone needs it.
[WCH55xISPDLL.zip](https://github.com/NgoHungCuong/vnproch551/files/3924252/WCH55xISPDLL.zip)

Currently my fork does work on CH552, but I don't have a CH551 now, and I'm not quite sure if we can remove the if statement in this commit https://github.com/DeqingSun/vnproch551/commit/440b1ee0bcdbb0ec1112c9faab55829115bef227 .
